const Handhelds = [
  // Calzones & Rolls
  { name: "CHICKEN ROLL", price: 8.95 },
  { name: "EGGPLANT ROLL", price: 8.95 },
  { name: "SAUSAGE & PEPPER ROLL", price: 8.95 },
  { name: "BROCCOLI, SPINACH & RICOTTA ROLL", price: 8.95 },
  { name: "MARINATED EGGPLANT ROLL", price: 8.95 },
  { name: "STROMBOLI", price: 8.95 },
  { name: "CALZONE", price: 8.95 },
  { name: "FRIED CALZONE", price: 9.95 },
  { name: "BUFFALO BITES", price: 6.95 },
  { name: "CHICKEN CLUB BITES", price: 7.95 },
  { name: "NONNA’S STUFFED GARLIC KNOTS", price: 6.95 },
  { name: "PINWHEELS", price: 3.95 },
  { name: "GARLIC KNOTS (6)", price: 3.50 },
  { name: "MR. VINNIE’S FAMOUS KNOTS", price: 7.95 },
  // Heros
  { name: "CHICKEN CUTLET HERO", price: 13.25 },
  { name: "BUFFALO CHICKEN HERO", price: 14.25 },
  { name: "CHICKEN BRUSCHETTA HERO", price: 15.25 },
  { name: "GRILLED CHICKEN HERO", price: 15.25 },
  { name: "GRILLED CHICKEN HERO (with Broccoli Rabe & Cherry Peppers)", price: 15.25 },
  { name: "MEATBALL HERO", price: 13.25 },
  { name: "SAUSAGE HERO", price: 13.25 },
  { name: "EGGPLANT HERO", price: 13.25 },
  { name: "VEAL CUTLET HERO", price: 17.25 },
  { name: "VEAL AND PEPPER HERO", price: 17.25 },
  { name: "SHRIMP HERO", price: 17.25 },
  { name: "EGG HERO", price: 13.25 },
  { name: "CHICKEN CLUB HERO", price: 15.25 },
  { name: "ITALIAN HERO (served cold)", price: 15.25 },
  { name: "CAPRESE HERO (served cold)", price: 15.25 },
  // Panini
  { name: "BROCCOLI RABE & SAUSAGE (Panini)", price: 14.95 },
  { name: "GRILLED CHICKEN, BROCCOLI RABE & CHERRY PEPPERS (Panini)", price: 14.95 },
  { name: "GRILLED CHICKEN, FRESH MOZZARELLA & TOMATOES (Panini)", price: 14.95 },
  { name: "BUFFALO CHICKEN WITH MELTED MOZZARELLA (Panini)", price: 14.95 },
  { name: "FRESH MOZZARELLA, TOMATOES, ROASTED PEPPER & BASIL (Panini)", price: 14.95 },
  // Wraps
  { name: "CHICKEN CLUB WRAP", price: 14.45 },
  { name: "GRILLED CHICKEN CAESAR WRAP", price: 14.45 },
  { name: "GREEK SALAD WITH CHICKEN WRAP", price: 14.45 },
  { name: "BALSAMIC CHICKEN WRAP", price: 14.45 },
  { name: "BUFFALO CHICKEN WRAP", price: 14.45 },
  { name: "CAPRESE WRAP", price: 14.45 },
  { name: "CHICKEN PARMIGIANA WRAP", price: 14.45 },
  { name: "EGGPLANT PARMIGIANA WRAP", price: 14.45 },
  { name: "MEATBALL PARMIGIANA WRAP", price: 14.45 },
  { name: "VEAL PARMIGIANA WRAP", price: 16.45 },
  { name: "SHRIMP PARMIGIANA WRAP", price: 16.45 },
  { name: "PEPPER & EGG WRAP", price: 14.45 },
];

export default Handhelds;
