const Starters = [
  // Rice Balls
  { name: "RICE BALL", price: 9.45 },
  { name: "RICE BALL SPECIAL", price: 12.45 },
  { name: "RICE BALL ALLA VODKA", price: 12.45 },
  { name: "RICE BALL PARMIGIANA", price: 12.45 },
  { name: "RICE BALL BOLOGNESE", price: 12.45 },
  // Fresh Salads
  { name: "RIELLA’S SALAD (Small)", price: 9.75 },
  { name: "RIELLA’S SALAD (Large)", price: 12.75 },
  { name: "ANTIPASTO (Chopped Only)", price: 23.95 },
  { name: "GIANFRANCO (Served Warm)", price: 23.95 },
  { name: "CAESAR SALAD", price: 14.95 },
  { name: "GREEK SALAD", price: 19.95 },
  { name: "BALSAMIC CHICKEN SALAD", price: 19.95 },
  { name: "BUFFALO CHICKEN SALAD", price: 19.95 },
  // Soups (using pint prices)
  { name: "TORTELLINI AL BRODO (Pint)", price: 9.95 },
  { name: "MINESTRONE (Pint)", price: 9.95 },
  { name: "PASTA E FAGIOLI (Pint)", price: 9.95 },
  { name: "STRACCELLA ALLA ROMANA (Pint)", price: 9.95 },
  { name: "CHICKEN NOODLE (Pint)", price: 9.95 },
  { name: "ITALIAN WEDDING (Pint)", price: 9.95 },
  { name: "RIELLA’S CLAM SOUP (Pint)", price: 9.95 },
  // Appetizers
  { name: "MOZZARELLA DI VITA", price: 22.95 },
  { name: "BAKED CLAMS", price: 22.95 },
  { name: "MUSSELS VINCENZO", price: 23.95 },
  { name: "ZUPPA DI MUSSELS (Red)", price: 21.95 },
  { name: "ZUPPA DI MUSSELS (White)", price: 21.95 },
  { name: "ZUPPA DI CLAMS (Red)", price: 21.95 },
  { name: "ZUPPA DI CLAMS (White)", price: 22.95 },
  { name: "CALAMARI ARRABBIATA (Red)", price: 25.95 },
  { name: "CALAMARI ARRABBIATA (White)", price: 25.95 },
  { name: "FRIED CALAMARI", price: 23.95 },
  { name: "PEPPERS & ONIONS", price: 18.75 },
  { name: "MARINATED EGGPLANT", price: 19.95 },
  { name: "STUFFED MUSHROOMS", price: 19.95 },
  { name: "FRIED ZUCCHINI", price: 17.95 },
  { name: "FRIED MOZZARELLA WEDGES", price: 17.95 },
  { name: "FRIED RAVIOLI", price: 15.95 },
  { name: "CHICKEN FINGERS", price: 15.95 },
  { name: "GARLIC BREAD", price: 7.95 },
  { name: "WINGS (12)", price: 21.95 },
  { name: "WINGS (6)", price: 14.95 },
  { name: "BONELESS WINGS", price: 21.95 },
];

export default Starters;
